= BSides Las Vegas 2015

:published_at: 2015-08-27

I was lucky enough to go to hacker mecha. For me this included the "OG" BSides in Las Vegas. I have attended/volunteered at every BSides Tampa and Orlando, and Las Vegas had the same feeling. People were open for conversation, and it felt like a place to freely meet people and exchange ideas. +


This year I took the extra step and decided to present. One amazing part of the Las Vegas BSides (and some others) is that they offer a newbie track (formally called the Proving Ground track.) There is a seperate earlier CFP submission process, where they pair you up with a mentor to assist in your talk. This was the track I selected because of lack in presentation experience. If anyone is feeling nervious about presenting, I would HIGHLY recommend submitting for Proving Ground. I was paired with my mentor Russel (@tcstoolHax0r) who had experience in my topic of SIEMs. He walked me though all the minor things that wouldn't come to mind: slide amount, density, etc and also helped with the flow of my talk while also suggesting areas to expand upon for my talk.
